### ISSUE TITLE
Please upload or provide this dataset

### ISSUE THREAD

**Issue by dilshans2k** [jeffheaton/t81_558_deep_learning#106]
Hello Sir
First of all thank you for creating such an awesome course and also making it available to general public via youtube.
So i was following this notebook t81_558_class_07_2_Keras_gan.ipynb and i found https://www.kaggle.com/gasgallo/lag-dataset is missing. Is there any way we can access this dataset. And also what is use of lag-dataset, You havent explained much about it in video.

**Comment by jeffheaton** [comment]
That is just a dataset of faces, there are several on the internet.  They do tend to come and go due to copyright issues sometimes surfacing.  I did some quick research and this seems to be the case with the lag-dataset, so Kaggle deleted it.  Thanks for the info on the broken link, I just removed it.  I have no ownership of this dataset, so I cannot upload the copy I used. Really, though, you can use any images you want so long as you format them to all have the same resolution.
