### ISSUE TITLE
Create environment fails - tensorflow-deps

### ISSUE THREAD

**Issue by SaschaHeyer** [jeffheaton/t81_558_deep_learning#116]
Hi

followed this steps 
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb

Unfortunately, this step fails:
```
conda env create -f tensorflow-apple-metal.yml -n tensorflow
```

With the following error message:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - tensorflow-deps
```

Best regards
Sascha

**Comment by jeffheaton** [comment]
This usually happens when you had a Python installed before installing miniforge.  I suggest running the command "which python", which will give you the paths to all pythons installed.  Look at the top one, if it is not miniforge (installed by Brew) then you will get this error.  Suggest looking at the "~/.kshrc" file and make sure it has the path to your miniforge installation.

**Comment by jeffheaton** [comment]
My students run into this issue too.  Basically, previous versions of Python are staying as the default path, and when you try to install **tensorflow-deps** it fails, because that is only a "miniforge" package, generally.  More info here:

https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb
