### ISSUE TITLE
Newer version of sklearn issues

### ISSUE THREAD

**Issue by rajans** [jeffheaton/t81_558_deep_learning#5]
Great lecture. Having issues with class 3 code in IBM DSWB.  Keep getting this error below but if I change it to cross_validation, it works

ImportError: No module named 'sklearn.model_selection'

Thanks
Sunder

**Comment by jeffheaton** [comment]
That is due to them having an outdated version of SK-Learn.  The current version moved the location of the kfold and train/test split classes.  

For more information, see Class 3 (https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class3_training.ipynb), and look at the section 
"Scikit-Learn Versions: model_selection vs cross_validation"

Just modify the code for the old way and it should work okay.
